__version__ = "0.1.0"
__name__ = "airtable_client"
__description__ = "Python API Wrapper for the Airtable API"
__url__ = "https://github.com/shikumiya/airtable_client"
__author__ = "shikumiya"
__authoremail__ = "info@shikumiya.co.jp"
__license__ = "The MIT License (MIT)"
__copyright__ = "Copyright 2020 Shikumiya, Inc."